# Generated by Django 5.1.5 on 2025-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_remove_department_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parents',
            new_name='Parent',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
